######################## default configuration ####################
baseURL = "https://area402.net/"
BasePath = '/'
title = "area402.net"
theme = "bigspring"
languageName = "De"
languageCode = "de-de"
DefaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

#################### default parameters ################################
[params]
logo = ""
logo_width = "200px"

author = "area402.net"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io


# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[languages.en.params.navigation_button]
enable = true
label = "Contact Us"
link = "contact"

[languages.de.params.navigation_button]
enable = true
label = "Kontakt"
link = "contact"



[languages]
  [languages.en]
    weight = 1
    [languages.en.params]
      description="en"
      footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
      copyright = ""

  [languages.de]
    weight = 1
    [languages.de.params]
      description="de"
      footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
      copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################

# main menu
[[languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 1

[[languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 3

[[languages.de.menu.main]]
name = "Blog"
URL = "blog"
weight = 1

[[languages.de.menu.main]]
name = "Kontakt"
URL = "contact"
weight = 3


# company
[[menu.company]]
name = "About Us"
URL = "#"

[[menu.company]]
name = "Quick Start"
URL = "#"

[[menu.company]]
name = "Pricing"
URL = "pricing"


# Product
[[menu.product]]
name = "Pricing"
URL = "pricing"

[[menu.product]]
name = "Platform"
URL = "#"

[[menu.product]]
name = "Features"
URL = "#"

# Support
[[menu.support]]
name = "Privacy Policy"
URL = "privacy-policy"

[[menu.support]]
name = "Terms & Conditions"
URL = "terms-conditions"

[[menu.support]]
name = "FAQ"
URL = "faq"


############################# social site ########################
# [[params.social]]
# title = "facebook"
# icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# title = "twitter"
# icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
# link = "#"

